[package]
name = "discovery-entities"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
